
DELETE  http://localhost:3003/api/blogs/5ddd051cd579821de4bf2682
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNpbHZhIiwiaWQiOiI1ZGRiZWE2MTIxOGVlOTNjZWNjNGExMzAiLCJpYXQiOjE1NzQ3NjgzODl9.pywMsk0JdPmDZe-F8WJx4kpt44wezRfODriN5Go-HZ0

POST http://localhost:3003/api/login
Content-Type: application/json

{
   "username": "Silva",
   "password": "Pinka"
}

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNvdWxBZG9yIiwiaWQiOiI1ZGRiZWEyZTIxOGVlOTNjZWNjNGExMmYiLCJpYXQiOjE1NzQ3NjM4NTl9.Gu6AwF2nyH2xk-p_siK7zzfBiGtNvZjPRovEPv36sng

{
   "title": "Token3",
   "author": "Andrew",
   "url": "TokTok",
   "likes": "232"
}


POST http://localhost:3003/api/users
Content-Type: application/json

{
   "username": "Silva",
   "name": "The greatest",
   "password": "Pinka"
}